// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: center.proto

package center

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid uint32 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Gateid uint32 `protobuf:"varint,2,opt,name=gateid,proto3" json:"gateid,omitempty"`
	Connid uint32 `protobuf:"varint,3,opt,name=connid,proto3" json:"connid,omitempty"`
}

func (x *ConnInfo) Reset() {
	*x = ConnInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnInfo) ProtoMessage() {}

func (x *ConnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnInfo.ProtoReflect.Descriptor instead.
func (*ConnInfo) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{0}
}

func (x *ConnInfo) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *ConnInfo) GetGateid() uint32 {
	if x != nil {
		return x.Gateid
	}
	return 0
}

func (x *ConnInfo) GetConnid() uint32 {
	if x != nil {
		return x.Connid
	}
	return 0
}

// 添加连接信息
type AddConnInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ConnInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *AddConnInfoReq) Reset() {
	*x = AddConnInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConnInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnInfoReq) ProtoMessage() {}

func (x *AddConnInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnInfoReq.ProtoReflect.Descriptor instead.
func (*AddConnInfoReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{1}
}

func (x *AddConnInfoReq) GetInfo() *ConnInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AddConnInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddConnInfoResp) Reset() {
	*x = AddConnInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConnInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnInfoResp) ProtoMessage() {}

func (x *AddConnInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnInfoResp.ProtoReflect.Descriptor instead.
func (*AddConnInfoResp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{2}
}

// 删除连接信息
type DelConnInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateid uint32 `protobuf:"varint,1,opt,name=gateid,proto3" json:"gateid,omitempty"`
	Connid uint32 `protobuf:"varint,2,opt,name=connid,proto3" json:"connid,omitempty"`
}

func (x *DelConnInfoReq) Reset() {
	*x = DelConnInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoReq) ProtoMessage() {}

func (x *DelConnInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoReq.ProtoReflect.Descriptor instead.
func (*DelConnInfoReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{3}
}

func (x *DelConnInfoReq) GetGateid() uint32 {
	if x != nil {
		return x.Gateid
	}
	return 0
}

func (x *DelConnInfoReq) GetConnid() uint32 {
	if x != nil {
		return x.Connid
	}
	return 0
}

type DelConnInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelConnInfoResp) Reset() {
	*x = DelConnInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoResp) ProtoMessage() {}

func (x *DelConnInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoResp.ProtoReflect.Descriptor instead.
func (*DelConnInfoResp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{4}
}

// 根据gateid删除连接信息
type DelConnInfoByGateidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateid uint32 `protobuf:"varint,1,opt,name=gateid,proto3" json:"gateid,omitempty"`
}

func (x *DelConnInfoByGateidReq) Reset() {
	*x = DelConnInfoByGateidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoByGateidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoByGateidReq) ProtoMessage() {}

func (x *DelConnInfoByGateidReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoByGateidReq.ProtoReflect.Descriptor instead.
func (*DelConnInfoByGateidReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{5}
}

func (x *DelConnInfoByGateidReq) GetGateid() uint32 {
	if x != nil {
		return x.Gateid
	}
	return 0
}

type DelConnInfoByGateidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelConnInfoByGateidResp) Reset() {
	*x = DelConnInfoByGateidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoByGateidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoByGateidResp) ProtoMessage() {}

func (x *DelConnInfoByGateidResp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoByGateidResp.ProtoReflect.Descriptor instead.
func (*DelConnInfoByGateidResp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{6}
}

// 获取所有的连接信息
type GetAllConnInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllConnInfoReq) Reset() {
	*x = GetAllConnInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllConnInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConnInfoReq) ProtoMessage() {}

func (x *GetAllConnInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConnInfoReq.ProtoReflect.Descriptor instead.
func (*GetAllConnInfoReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{7}
}

type GetAllConnInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*ConnInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetAllConnInfoResp) Reset() {
	*x = GetAllConnInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllConnInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConnInfoResp) ProtoMessage() {}

func (x *GetAllConnInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConnInfoResp.ProtoReflect.Descriptor instead.
func (*GetAllConnInfoResp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllConnInfoResp) GetInfos() []*ConnInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 新增连接信息通知
type NewConnInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ConnInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *NewConnInfoNotify) Reset() {
	*x = NewConnInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewConnInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConnInfoNotify) ProtoMessage() {}

func (x *NewConnInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConnInfoNotify.ProtoReflect.Descriptor instead.
func (*NewConnInfoNotify) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{9}
}

func (x *NewConnInfoNotify) GetInfo() *ConnInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 删除连接信息通知
type DelConnInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ConnInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *DelConnInfoNotify) Reset() {
	*x = DelConnInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoNotify) ProtoMessage() {}

func (x *DelConnInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoNotify.ProtoReflect.Descriptor instead.
func (*DelConnInfoNotify) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{10}
}

func (x *DelConnInfoNotify) GetInfo() *ConnInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 根据gateid删除连接信息通知
type DelConnInfoByGateidNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateid uint32 `protobuf:"varint,1,opt,name=gateid,proto3" json:"gateid,omitempty"`
}

func (x *DelConnInfoByGateidNotify) Reset() {
	*x = DelConnInfoByGateidNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelConnInfoByGateidNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnInfoByGateidNotify) ProtoMessage() {}

func (x *DelConnInfoByGateidNotify) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnInfoByGateidNotify.ProtoReflect.Descriptor instead.
func (*DelConnInfoByGateidNotify) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{11}
}

func (x *DelConnInfoByGateidNotify) GetGateid() uint32 {
	if x != nil {
		return x.Gateid
	}
	return 0
}

var File_center_proto protoreflect.FileDescriptor

var file_center_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61,
	0x74, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x43, 0x6f,
	0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x30, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x47, 0x61, 0x74, 0x65, 0x69,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17,
	0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x47, 0x61, 0x74,
	0x65, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x3c, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x39, 0x0a, 0x11, 0x4e, 0x65,
	0x77, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x39, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x33, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x79, 0x47, 0x61, 0x74, 0x65, 0x69, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x74, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x61, 0x74, 0x65, 0x69, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_center_proto_rawDescOnce sync.Once
	file_center_proto_rawDescData = file_center_proto_rawDesc
)

func file_center_proto_rawDescGZIP() []byte {
	file_center_proto_rawDescOnce.Do(func() {
		file_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_center_proto_rawDescData)
	})
	return file_center_proto_rawDescData
}

var file_center_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_center_proto_goTypes = []any{
	(*ConnInfo)(nil),                  // 0: center.ConnInfo
	(*AddConnInfoReq)(nil),            // 1: center.AddConnInfoReq
	(*AddConnInfoResp)(nil),           // 2: center.AddConnInfoResp
	(*DelConnInfoReq)(nil),            // 3: center.DelConnInfoReq
	(*DelConnInfoResp)(nil),           // 4: center.DelConnInfoResp
	(*DelConnInfoByGateidReq)(nil),    // 5: center.DelConnInfoByGateidReq
	(*DelConnInfoByGateidResp)(nil),   // 6: center.DelConnInfoByGateidResp
	(*GetAllConnInfoReq)(nil),         // 7: center.GetAllConnInfoReq
	(*GetAllConnInfoResp)(nil),        // 8: center.GetAllConnInfoResp
	(*NewConnInfoNotify)(nil),         // 9: center.NewConnInfoNotify
	(*DelConnInfoNotify)(nil),         // 10: center.DelConnInfoNotify
	(*DelConnInfoByGateidNotify)(nil), // 11: center.DelConnInfoByGateidNotify
}
var file_center_proto_depIdxs = []int32{
	0, // 0: center.AddConnInfoReq.info:type_name -> center.ConnInfo
	0, // 1: center.GetAllConnInfoResp.infos:type_name -> center.ConnInfo
	0, // 2: center.NewConnInfoNotify.info:type_name -> center.ConnInfo
	0, // 3: center.DelConnInfoNotify.info:type_name -> center.ConnInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_center_proto_init() }
func file_center_proto_init() {
	if File_center_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_center_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddConnInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddConnInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoByGateidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoByGateidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllConnInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllConnInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*NewConnInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DelConnInfoByGateidNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_center_proto_goTypes,
		DependencyIndexes: file_center_proto_depIdxs,
		MessageInfos:      file_center_proto_msgTypes,
	}.Build()
	File_center_proto = out.File
	file_center_proto_rawDesc = nil
	file_center_proto_goTypes = nil
	file_center_proto_depIdxs = nil
}
